" enable line numbers
set number

" highlight the line under the cursor
set cursorline

" something to do with preventing formatting from being mangled on paste
set formatoptions-=cr

" enable mouse interaction
set mouse=a
" setting 'mouse=a' also kills right-click paste, re-bind it
map <RightMouse> "+gP
" sync the system clipboard (ie: the one managed by X which in WSL comes via vcxsrv) with vim's clipboard
set clipboard=unnamedplus

" bind ^Up and ^Down to move lines up/down
nnoremap <C-Up> :m .-2<CR>==
nnoremap <C-Down> :m .+1<CR>==
inoremap <C-Up> <Esc>:m .-2<CR>==gi
inoremap <C-Down> <Esc>:m .+1<CR>==gi
vnoremap <C-Up> :m '<-2<CR>gv=gvi
vnoremap <C-Down> :m '>+1<CR>gv=gv

" highlight search results
set hlsearch

" tab control
set shiftwidth=4
set softtabstop=4
set expandtab

" move .swp file somewhere they wont be an eyesore
set directory=~/vim/tmp,/var/tmp,/tmp
" disable .swp file warning message
set shortmess=A

"-- vim-plug stuff ----------------------------------------

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin()
Plug 'preservim/nerdcommenter'
Plug 'terryma/vim-expand-region'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ayu-theme/ayu-vim'
call plug#end()

"-- toggle comments ---------------------------------------
filetype plugin on
let g:NERDCreateDefaultMappings = 1

"-- vim-airline -------------------------------------------
let g:airline_powerline_fonts = 1
source ~/.vim/patched-airline-ayu_mirage.vim

"-- set the color theme -----------------------------------
if (has('termguicolors'))
    set termguicolors
endif

syntax on
let ayucolor="mirage"
colorscheme ayu

" don't set the bacground for the normal windows (use the termial's bg)
hi Normal guibg=NONE ctermbg=NONE
