set number
set formatoptions-=cr

" enable mouse interaction
set mouse=a
" setting 'mouse=a' also kills right-click paste, re-bind it
map <RightMouse> "+gP
" sync the system clipboard (ie: the one managed by X which in WSL comes via vcxsrv) with vim's clipboard
set clipboard=unnamedplus
" bind ^Up and ^Down to move lines up/down
nnoremap <C-Up> :m .-2<CR>==
nnoremap <C-Down> :m .+1<CR>==
inoremap <C-Up> <Esc>:m .-2<CR>==gi
inoremap <C-Down> <Esc>:m .+1<CR>==gi
vnoremap <C-Up> :m '<-2<CR>gv=gvi
vnoremap <C-Down> :m '>+1<CR>gv=gv

set hlsearch
set shiftwidth=4
set softtabstop=4
set expandtab

" move .swp file somewhere they wont be an eyesore
set directory=~/vim/tmp,/var/tmp,/tmp
" disable .swp file warning message
set shortmess=A

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin()
Plug 'flrnd/candid.vim', { 'branch': 'main' }
Plug 'preservim/nerdcommenter'
call plug#end()

if (has('termguicolors'))
  set termguicolors
endif

set background=dark
syntax on 
colorscheme candid

" for nerd commenter
filetype plugin on
let g:NERDCreateDefaultMappings = 1
