config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_aliases.zsh:
    src: aliases.zsh
    dst: ~/.aliases.zsh
    chmod: '755'
  f_dircolors:
    src: dircolors
    dst: ~/.dircolors
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gpg-agent.conf:
    src: gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
    chmod: '600'
  f_gpg.conf:
    src: gnupg/gpg.conf
    dst: ~/.gnupg/gpg.conf
    chmod: '600'
  f_wsl-startx.sh:
    src: wsl-startx.sh
    dst: ~/wsl-startx.sh
    chmod: '755'
  f_vcxsrv.xlaunch:
    src: config/vcxsrv.xlaunch
    dst: ~/.config/vcxsrv.xlaunch
  f_patched-airline-ayu_mirage.vim:
    src: vim/patched-airline-ayu_mirage.vim
    dst: ~/.vim/patched-airline-ayu_mirage.vim
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_git-redate:
    src: bin/git-redate
    dst: ~/bin/git-redate
    chmod: '755'
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
    chmod: '755'
profiles:
  ROZZZLY-DESKTOP:
    dotfiles:
    - f_gitconfig
    - f_vimrc
    - f_zshrc
    - f_p10k.zsh
    - f_aliases.zsh
    - f_gpg-agent.conf
    - f_gpg.conf
    - f_wsl-startx.sh
    - f_vcxsrv.xlaunch
    - f_patched-airline-ayu_mirage.vim
    - f_zshenv
    - f_git-redate
    - f_config
