config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_aliases.zsh:
    src: aliases.zsh
    dst: ~/.aliases.zsh
    chmod: '755'
  f_dircolors:
    src: dircolors
    dst: ~/.dircolors
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
profiles:
  ROZZZLY-DESKTOP:
    dotfiles:
    - f_gitconfig
    - f_vimrc
    - f_zshrc
    - f_p10k.zsh
    - f_aliases.zsh
